### ISSUE TITLE
Increase token expiration time

### ISSUE THREAD

**Issue by aminuolawale** [aminuolawale/market_watcher#4]
The token expiration time should be increased from its current default value so that development is faster and one doesn't have to log in every 5 mins.

**Comment by wizzle3d** [comment]
I increased the access token lifetime to 60mins and the refresh token lifetime to 10days.

**Comment by aminuolawale** [comment]
Please open a PR (pull request) on your new branch.
You can open a pull request by clicking the branch list drop down on the repository page, selecting your branch and then clicking on contribute to open a PR. 
After this has been done, on the right side of this page, you can link the pull request to this issue by clicking on the gear icon beside `Linked pull requests`
